In [3]:
import seaborn as sns 
import pandas as pd

In [10]:
dict1 = {'x1':[ i for i in range(1,10)],
        'x2':[ i for i in range(11,20)],
        'x3':[ i for i in range(30,21,-1)],
        'x4':[ i for i in range(41,50)],
        'y':[ i for i in range(101,110)]}

In [11]:
df=pd.DataFrame(data=dict1)

In [12]:
df.corr()

     x1   x2   x3   x4    y
x1  1.0  1.0 -1.0  1.0  1.0
x2  1.0  1.0 -1.0  1.0  1.0
x3 -1.0 -1.0  1.0 -1.0 -1.0
x4  1.0  1.0 -1.0  1.0  1.0
y   1.0  1.0 -1.0  1.0  1.0

In [14]:
df1 = sns.load_dataset('tips')[['total_bill','tip','size']]

In [15]:
df1

     total_bill   tip  size
0         16.99  1.01     2
1         10.34  1.66     3
2         21.01  3.50     3
3         23.68  3.31     2
4         24.59  3.61     4
..          ...   ...   ...
239       29.03  5.92     3
240       27.18  2.00     2
241       22.67  2.00     2
242       17.82  1.75     2
243       18.78  3.00     2

[244 rows x 3 columns]